version: "3"
services:
  website:
    #   container_name: hotel
    network_mode: bridge
    build:
      context: ./
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=hotel
      - DB_USERNAME=hotel_admin
      - DB_PASSWORD=hotel_admin_password
    ports:
      - 8000:8000
    links:
      - mysql
    depends_on:
      - mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    network_mode: bridge
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=myroot
    ports:
      - 3000:80
    links:
      - mysql
      - website
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    network_mode: bridge
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: hotel
      MYSQL_USER: hotel_admin
      MYSQL_PASSWORD: hotel_admin_password
      MY_SQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
